
name: Analyze code with Sonarqube
on:
  workflow_call:
    secrets:
      SONARQUBE_HOST:
        required: true
      SONARQUBE_TOKEN:
        required: true
jobs:
  analyze-code:
    runs-on: ubuntu-20.04
    steps:
    - name: Checking out
      uses: actions/checkout@master
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
