
name: Deploy generic app in the cluster

on:
  workflow_call:
    inputs:
      K8S_RESOURCENAME: 
        type: string
        required: true
      K8S_ADDITIONAL_RESOURCE:
        type: string
        required: false
      K8S_NAMESPACE:
        required: true
        type: string
      K8S_OBJECTTYPE: 
        type: string
        required: true
      K8S_CONTAINERNAME:
        type: string
        required: true
    secrets:
      KUBECONFIG:
        required: true
      AWS_CREDENTIALS:
        required: false
jobs:
  update-kubernetes-resource:
    runs-on: self-hosted
    steps:
      - name: Extract Git Branch information
        id: branch_name
        run: |
          MBRANCH=${GITHUB_REF#refs/*/}
          BRANCH=${MBRANCH#feature/}
          echo "BRANCH: $BRANCH";
          if [[ "$BRANCH" == "develop" ]]; then BRANCH="$(BRANCH)$(date +%s)"; fi
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "DOCKERIMAGEANDTAG=${{ inputs.DOCKER_IMAGEBASE }}:$BRANCH" >> $GITHUB_OUTPUT
          echo "Started by: $GITHUB_ACTOR | SHA: $GITHUB_SHA | Tag: ${GITHUB_REF#refs/tags/}"

      - name: Generate patch command for kubectl
        if: ${{ !env.ACT }}
        id: patch_cmd
        run: |
          CMD='{"spec": {"template": {"spec": {"containers": [{"name":"${{ inputs.K8S_CONTAINERNAME }}","image": "${{ steps.branch_name.outputs.DOCKERIMAGEANDTAG }}"}] }}}}'
          if [ ${{ inputs.K8S_OBJECTTYPE }} == "cronjob" ]; then
          CMD='{"spec": {"jobTemplate": {"spec": {"template": {"spec": {"containers": [{"name":"${{ inputs.K8S_CONTAINERNAME }}","image": "${{ steps.branch_name.outputs.DOCKERIMAGEANDTAG }}"}] }}}}}}' ;
          fi
          echo Going to execute : $CMD
          echo "K8SPATCH=$CMD" >> $GITHUB_OUTPUT

      - name: Add github-cd User to AWS Credentials file
        continue-on-error: true
        run: echo "${{ secrets.AWS_CREDENTIALS }}" > /root/.aws/credentials

      - name: Create kubeconfig
        run: echo ${{ secrets.KUBECONFIG }} | base64 --decode > /root/.kube/config

      - name: Update version in Cluster
        if: ${{ !env.ACT }}
        run: "kubectl --insecure-skip-tls-verify patch ${{ inputs.K8S_OBJECTTYPE }} ${{ inputs.K8S_RESOURCENAME }} ${{ inputs.K8S_ADDITIONAL_RESOURCE }} -n ${{ inputs.K8S_NAMESPACE }} --patch '${{ steps.patch_cmd.outputs.K8SPATCH }}'"

      - name: Redeploy
        if: ${{ (!env.ACT) && (inputs.K8S_OBJECTTYPE != 'cronjob') }}
        run: "kubectl --insecure-skip-tls-verify rollout restart ${{ inputs.K8S_OBJECTTYPE }} ${{ inputs.K8S_RESOURCENAME }} ${{ inputs.K8S_ADDITIONAL_RESOURCE }} -n ${{ inputs.K8S_NAMESPACE }}"

      - name: Verify Deployment
        if: ${{ (!env.ACT) && (inputs.K8S_OBJECTTYPE != 'cronjob') }}
        run: "kubectl --insecure-skip-tls-verify rollout status ${{ inputs.K8S_OBJECTTYPE }} ${{ inputs.K8S_RESOURCENAME }} -n ${{ inputs.K8S_NAMESPACE }} --timeout=4m"

