
name: Generic Kubernetes Deploy for serverless apps

on:
  workflow_call:
    inputs:
      DOCKER_IMAGEBASE:
        required: true
        type: string
      K8S_RESOURCENAME:
        type: string
        required: true
      K8S_ADDITIONAL_RESOURCE:
        type: string
        required: false
      K8S_NAMESPACE:
        required: true
        type: string
    secrets:
      KUBECONFIG:
        required: true
      AWS_CREDENTIALS:
        required: false

jobs:
  update-kubernetes-resource:
    runs-on: self-hosted
    steps:
      - name: Add github-cd User to AWS Credentials file
        continue-on-error: true
        run: echo "${{ secrets.AWS_CREDENTIALS }}" > /root/.aws/credentials

      - name: Extract Git Branch information
        id: branch_name
        run: |
          MBRANCH=${GITHUB_REF#refs/*/}
          GITSHA=${GITHUB_SHA::8}
          BRANCH=${MBRANCH#feature/}
          echo "$BRANCH";
          if [[ "$BRANCH" == "develop" ]]; then BRANCH="$(BRANCH)$(date +%s)"; fi
          echo ::set-output name=SOURCE_NAME::$BRANCH
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
          echo ::set-output name=DOCKERIMAGEANDTAG::${{ inputs.DOCKER_IMAGEBASE }}:$BRANCH
          echo SOURCE_NAME $SOURCE_NAME $BRANCH ~ALSO~ SOURCE_TAG $SOURCE_TAG ~ALSO~ SHA $GITSHA

      - name: Create kubeconfig
        run: echo ${{ secrets.KUBECONFIG }} | base64 --decode > /root/.kube/config
      
      - name: Update version in Cluster
        if: ${{ !env.ACT }}
        run: "kn service update ${{ inputs.K8S_RESOURCENAME }} --image=${{ steps.branch_name.outputs.DOCKERIMAGEANDTAG }} -n ${{ inputs.K8S_NAMESPACE }}"
